name: Michel Moura Silva blog
description: Irei compartilhar alguns conhecimentos adquiridos durante esses anos na área de TI, seja algo que estou aprendendo no momento ou projetos no qual estou trabalhando ou trabalhei.
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://michelmourasilva.github.io'
google_analytics: 'UA-134337142-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
